# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'chatapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for chatapp
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'tvOS',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  # post_install do |installer|
  #     installer.pods_project.targets.each do |target|
  #         if target.name == 'yoga'
  #             target.build_configurations.each do |config|
  #                 config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
  #                 config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
  #             end
  #         end
  #     end
  # end
end
